import type { Metadata } from "next";
import "./globals.css";
import { TripCartProvider } from "./components/TripCartContext";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#FFFDF6] font-sans text-[#1A1A1A] px-4 w-full">
        {/* TripCartProvider gives cart context to the whole app */}
        <TripCartProvider>
          <Navbar />
          {children}
        </TripCartProvider>
      </body>
    </html>
  );
}
